spring:
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=15m
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  admin:
    email: ${ADMIN_EMAIL}
  yookassa:
    shop-id: ${YOOKASSA_SHOP_ID}
    secret-key: ${YOOKASSA_SECRET_KEY}
  mail:
    from: ${MAIL_FROM}

server:
  servlet:
    session:
      cookie:
        name: PULSECORE_SESSION
        secure: false