
spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
            scope:
              - login:email
              - login:info
              - login:default_phone
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:}
  session:
    timeout: 5m

logging:
  level:
    root: info
    ru.pulsecore.app: warn
    org.springframework: WARN
    org.hibernate: WARN
    ru.pulsecore.app.tournament.application.discovery.DiscoveryNotificationService: info
    ru.pulsecore.app.tournament.application.discovery.TournamentDiscoveryService: info
    ru.pulsecore.app.player.application.analytic.PrimaryLeagueUpdater: INFO
    ru.pulsecore.app.tournament.application.tournament.finish.TournamentFinishService: INFO
    ru.pulsecore.app.tournament.application.finish.TournamentFinishService: info
    ru.pulsecore.app.tournament.application.ResultService: info
    ru.pulsecore.app.tournament.application.lineup.LineupCleanupService: info
    ru.pulsecore.app.tournament.application.lineup.LineupUpsertService: info
    ru.pulsecore.app.tournament.application.discovery.TournamentSaver: info
    ru.pulsecore.app.tournament.application.cascade.TournamentAutoAddService: info





app:
  base-url: http://localhost:8080
  qr-color: "#14b8a6"

server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false