spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/yandex"
            scope:
              - login:email
              - login:info
              - login:default_phone
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:}
  session:
    timeout: 5m

spring doc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: WARN
    org.apache.pdfbox.pdmodel.font.PDType1Font: ERROR
    ru.pulsecore.app: debug
    org.springframework: WARN
    org.hibernate: WARN
#    org.hibernate.SQL: DEBUG           # ← SQL-запросы
#    org.hibernate.orm.jdbc.bind: TRACE # ← параметры (product_id = 1)







app:
  base-url: http://localhost:8080
  qr-color: "#14b8a6"



server:
  address: 0.0.0.0  # ← слушать все интерфейсы
  port: 8080
  servlet:
    session:
      cookie:
        secure: false